package apperr

const (
	PLATFORM_INTERNAL_ERROR         = "PLATFORM_INTERNAL_ERROR"
	PLATFORM_REQUEST_INVALID        = "PLATFORM_REQUEST_INVALID"
	PLATFORM_DEPENDENCY_UNAVAILABLE = "PLATFORM_DEPENDENCY_UNAVAILABLE"

	PLATFORM_AUTH_MISSING_API_KEY = "PLATFORM_AUTH_MISSING_API_KEY"
	PLATFORM_AUTH_INVALID_API_KEY = "PLATFORM_AUTH_INVALID_API_KEY"
	PLATFORM_AUTH_FORBIDDEN       = "PLATFORM_AUTH_FORBIDDEN"
	
	PLATFORM_CONFLICT = "PLATFORM_CONFLICT"

	UPSTREAM_TIMEOUT     = "UPSTREAM_TIMEOUT"
	UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
)